### PR TITLE
Mostly working manifest for building TWRP in an Omni 6.0 tree

### PR DESCRIPTION
**Pull request by zhuowei**

### CODE REVIEW

**Comment by marduk191** [comment]
Did you test this? If so, on what device

**Comment by zhuowei** [comment]
@marduk191 I was using this with a few more repos to build for Nexus 6P (Angler): I'll double check if I've missed anything

**Comment by marduk191** [comment]
@zhuowei Alright, I have a couple of birthday parties to attend today, I'll check it out this weekend and see.

**Comment by marduk191** [comment]
Added it as your branch. Also updated the readme. Please submit pull requests to the "zhuowei-android-6.0" branch if you find any errors.

**Pull request closed without merging**
