### PR TITLE
Android 5.1: adding mandatory component

### PR DESCRIPTION
**Pull request by ast261**
https://github.com/marduk191/recovery_manifest/commit/d60de80bd5be0ca300c4327c611bc4489368e51c

### CODE REVIEW

**Comment by ast261** [comment]
sorry, please ignore README :-)

**Comment by marduk191** [comment]
@ast261 is this needed for a specific device,  or always needed in 5.1?

**Comment by ast261** [comment]
Always needed.

**Comment by marduk191** [comment]
@ast261 fix the readme in your fork so that the pull will be corrected. Then I'll merge

**Comment by ast261** [comment]
OK, I will do.
BTW:
Are you planning a 6.0 branch ?

**Comment by marduk191** [comment]
@ast261 myself,  no telling.  I didn't even test 5.1 lol. Feel free to push one here since I guess troy is linking this in a tutorial.

**Comment by ast261** [comment]
I fixed the README

**Comment by marduk191** [comment]
@ast261 Merged and fixed up the readme a little. Thanks.

**Pull request merged**
